// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/employee_profile.proto

package org.grpc_server.proto;

public final class EmployeeProfileOuterClass {
  private EmployeeProfileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_grpc_server_proto_EmployeeProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_grpc_server_proto_EmployeeProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_grpc_server_proto_EmployeeError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_grpc_server_proto_EmployeeError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037messages/employee_profile.proto\022\025org.g" +
      "rpc_server.proto\"=\n\017EmployeeProfile\022\023\n\013e" +
      "mployee_id\030\001 \001(\003\022\025\n\remployee_name\030\002 \001(\t\"" +
      "$\n\rEmployeeError\022\023\n\013description\030\001 \001(\tB\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_grpc_server_proto_EmployeeProfile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_grpc_server_proto_EmployeeProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_grpc_server_proto_EmployeeProfile_descriptor,
        new java.lang.String[] { "EmployeeId", "EmployeeName", });
    internal_static_org_grpc_server_proto_EmployeeError_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_grpc_server_proto_EmployeeError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_grpc_server_proto_EmployeeError_descriptor,
        new java.lang.String[] { "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
