// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee_service.proto

package org.grpc_server.proto;

public final class EmployeeServiceOuterClass {
  private EmployeeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026employee_service.proto\022\025org.grpc_serve" +
      "r.proto\032\033google/protobuf/empty.proto\032\036go" +
      "ogle/protobuf/wrappers.proto\032\037messages/e" +
      "mployee_profile.proto2\252\004\n\017EmployeeServic" +
      "e\022T\n\013GetEmployee\022\033.google.protobuf.Int64" +
      "Value\032&.org.grpc_server.proto.EmployeePr" +
      "ofile\"\000\022_\n\013AddEmployee\022&.org.grpc_server" +
      ".proto.EmployeeProfile\032&.org.grpc_server" +
      ".proto.EmployeeProfile\"\000\022K\n\016DeleteEmploy" +
      "ee\022\033.google.protobuf.Int64Value\032\032.google" +
      ".protobuf.BoolValue\"\000\022R\n\014ClientStream\022&." +
      "org.grpc_server.proto.EmployeeProfile\032\026." +
      "google.protobuf.Empty\"\000(\001\022R\n\014ServerStrea" +
      "m\022\026.google.protobuf.Empty\032&.org.grpc_ser" +
      "ver.proto.EmployeeProfile\"\0000\001\022k\n\023BiDirec" +
      "tionalStream\022&.org.grpc_server.proto.Emp" +
      "loyeeProfile\032&.org.grpc_server.proto.Emp" +
      "loyeeProfile\"\000(\0010\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          org.grpc_server.proto.EmployeeProfileOuterClass.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    org.grpc_server.proto.EmployeeProfileOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
