// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/employee_profile.proto

package org.grpc_server.proto;

public interface EmployeeErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.grpc_server.proto.EmployeeError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
