// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/employee_profile.proto

package org.grpc_server.proto;

/**
 * Protobuf type {@code org.grpc_server.proto.EmployeeProfile}
 */
public final class EmployeeProfile extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.grpc_server.proto.EmployeeProfile)
    EmployeeProfileOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeProfile.newBuilder() to construct.
  private EmployeeProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeProfile() {
    employeeName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeProfile();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeProfile(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            employeeId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            employeeName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.grpc_server.proto.EmployeeProfileOuterClass.internal_static_org_grpc_server_proto_EmployeeProfile_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.grpc_server.proto.EmployeeProfileOuterClass.internal_static_org_grpc_server_proto_EmployeeProfile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.grpc_server.proto.EmployeeProfile.class, org.grpc_server.proto.EmployeeProfile.Builder.class);
  }

  public static final int EMPLOYEE_ID_FIELD_NUMBER = 1;
  private long employeeId_;
  /**
   * <code>int64 employee_id = 1;</code>
   * @return The employeeId.
   */
  @java.lang.Override
  public long getEmployeeId() {
    return employeeId_;
  }

  public static final int EMPLOYEE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object employeeName_;
  /**
   * <code>string employee_name = 2;</code>
   * @return The employeeName.
   */
  @java.lang.Override
  public java.lang.String getEmployeeName() {
    java.lang.Object ref = employeeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employeeName_ = s;
      return s;
    }
  }
  /**
   * <code>string employee_name = 2;</code>
   * @return The bytes for employeeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmployeeNameBytes() {
    java.lang.Object ref = employeeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employeeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (employeeId_ != 0L) {
      output.writeInt64(1, employeeId_);
    }
    if (!getEmployeeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, employeeName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (employeeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, employeeId_);
    }
    if (!getEmployeeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, employeeName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.grpc_server.proto.EmployeeProfile)) {
      return super.equals(obj);
    }
    org.grpc_server.proto.EmployeeProfile other = (org.grpc_server.proto.EmployeeProfile) obj;

    if (getEmployeeId()
        != other.getEmployeeId()) return false;
    if (!getEmployeeName()
        .equals(other.getEmployeeName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPLOYEE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEmployeeId());
    hash = (37 * hash) + EMPLOYEE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmployeeName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.grpc_server.proto.EmployeeProfile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.grpc_server.proto.EmployeeProfile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.grpc_server.proto.EmployeeProfile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.grpc_server.proto.EmployeeProfile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.grpc_server.proto.EmployeeProfile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.grpc_server.proto.EmployeeProfile)
      org.grpc_server.proto.EmployeeProfileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.grpc_server.proto.EmployeeProfileOuterClass.internal_static_org_grpc_server_proto_EmployeeProfile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.grpc_server.proto.EmployeeProfileOuterClass.internal_static_org_grpc_server_proto_EmployeeProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.grpc_server.proto.EmployeeProfile.class, org.grpc_server.proto.EmployeeProfile.Builder.class);
    }

    // Construct using org.grpc_server.proto.EmployeeProfile.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employeeId_ = 0L;

      employeeName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.grpc_server.proto.EmployeeProfileOuterClass.internal_static_org_grpc_server_proto_EmployeeProfile_descriptor;
    }

    @java.lang.Override
    public org.grpc_server.proto.EmployeeProfile getDefaultInstanceForType() {
      return org.grpc_server.proto.EmployeeProfile.getDefaultInstance();
    }

    @java.lang.Override
    public org.grpc_server.proto.EmployeeProfile build() {
      org.grpc_server.proto.EmployeeProfile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.grpc_server.proto.EmployeeProfile buildPartial() {
      org.grpc_server.proto.EmployeeProfile result = new org.grpc_server.proto.EmployeeProfile(this);
      result.employeeId_ = employeeId_;
      result.employeeName_ = employeeName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.grpc_server.proto.EmployeeProfile) {
        return mergeFrom((org.grpc_server.proto.EmployeeProfile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.grpc_server.proto.EmployeeProfile other) {
      if (other == org.grpc_server.proto.EmployeeProfile.getDefaultInstance()) return this;
      if (other.getEmployeeId() != 0L) {
        setEmployeeId(other.getEmployeeId());
      }
      if (!other.getEmployeeName().isEmpty()) {
        employeeName_ = other.employeeName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.grpc_server.proto.EmployeeProfile parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.grpc_server.proto.EmployeeProfile) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long employeeId_ ;
    /**
     * <code>int64 employee_id = 1;</code>
     * @return The employeeId.
     */
    @java.lang.Override
    public long getEmployeeId() {
      return employeeId_;
    }
    /**
     * <code>int64 employee_id = 1;</code>
     * @param value The employeeId to set.
     * @return This builder for chaining.
     */
    public Builder setEmployeeId(long value) {
      
      employeeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 employee_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployeeId() {
      
      employeeId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object employeeName_ = "";
    /**
     * <code>string employee_name = 2;</code>
     * @return The employeeName.
     */
    public java.lang.String getEmployeeName() {
      java.lang.Object ref = employeeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employeeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employee_name = 2;</code>
     * @return The bytes for employeeName.
     */
    public com.google.protobuf.ByteString
        getEmployeeNameBytes() {
      java.lang.Object ref = employeeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employee_name = 2;</code>
     * @param value The employeeName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployeeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employeeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employee_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmployeeName() {
      
      employeeName_ = getDefaultInstance().getEmployeeName();
      onChanged();
      return this;
    }
    /**
     * <code>string employee_name = 2;</code>
     * @param value The bytes for employeeName to set.
     * @return This builder for chaining.
     */
    public Builder setEmployeeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employeeName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.grpc_server.proto.EmployeeProfile)
  }

  // @@protoc_insertion_point(class_scope:org.grpc_server.proto.EmployeeProfile)
  private static final org.grpc_server.proto.EmployeeProfile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.grpc_server.proto.EmployeeProfile();
  }

  public static org.grpc_server.proto.EmployeeProfile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeProfile>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeProfile>() {
    @java.lang.Override
    public EmployeeProfile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeProfile(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeProfile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeProfile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.grpc_server.proto.EmployeeProfile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

