// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/employee_profile.proto

package org.grpc_server.proto;

public interface EmployeeProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.grpc_server.proto.EmployeeProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 employee_id = 1;</code>
   * @return The employeeId.
   */
  long getEmployeeId();

  /**
   * <code>string employee_name = 2;</code>
   * @return The employeeName.
   */
  java.lang.String getEmployeeName();
  /**
   * <code>string employee_name = 2;</code>
   * @return The bytes for employeeName.
   */
  com.google.protobuf.ByteString
      getEmployeeNameBytes();
}
